#!/bin/bash

trayer \
    --edge top \
    --align right \
    --SetDockType true \
    --SetPartialStrut true \
    --expand false \
    --widthtype pixel \
    --width 120 \
    --heighttype pixel \
    --height 15 \
    --transparent true \
    --tint 0x191970 \
    --monitor primary &

# set neo layout as default (to switch use aliases defined in .zshrc)
setxkbmap de
xmodmap "${HOME}/dotfiles/neo_de.xmodmap"
xmodmap "${HOME}/dotfiles/swap_ctrl_altgr.xmodmap"

start_dropbox() {
    local dropboxd="$(which dropbox)"
    test -e "${dropboxd}" || dropboxd="${HOME}/.dropbox-dist/dropboxd"
    if test -e "${dropboxd}"; then
	${dropboxd} start&
    fi
}

#pidgin&
start_dropbox
urxvtd -q -o -f
# I don't need NM on my tower…
if [[ $(hostname) != "taris" ]]; then
    ck-launch-session nm-applet&
fi
gtk-redshift&

xset b off
